eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: ToDo-Config-Server
  cloud: 
    config:
      server: 
        git: 
          uri: https://github.com/sameer9314/ToDoProperties.git  
      profile: prod
  profiles:
    active:
    - prod
    
server:
  port: 8888